apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "my-cluster-kafka-bootstrap:9092"
  - name: authRequired
    value: "false"
  - name: consumerGroup
    value: "todo-backend-group"
  - name: clientID
    value: "todo-backend-client"
